// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN41iYxOHkvh4AgXFDXra3eA-KgGLmIwY',
    appId: '1:26798202385:web:222f46c8fc57dc95639bb0',
    messagingSenderId: '26798202385',
    projectId: 'myriads-39550',
    authDomain: 'myriads-39550.firebaseapp.com',
    storageBucket: 'myriads-39550.appspot.com',
    measurementId: 'G-Q18HRTHMWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGH22JejaFhQcYLmLpkxCKQZmUIaITwIc',
    appId: '1:26798202385:android:c714fef6822067ec639bb0',
    messagingSenderId: '26798202385',
    projectId: 'myriads-39550',
    storageBucket: 'myriads-39550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHrFFIRjtLiFG1IugzXbV-q3jHYY29m0',
    appId: '1:26798202385:ios:ed19ea344f94debb639bb0',
    messagingSenderId: '26798202385',
    projectId: 'myriads-39550',
    storageBucket: 'myriads-39550.appspot.com',
    iosBundleId: 'com.example.myriads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIHrFFIRjtLiFG1IugzXbV-q3jHYY29m0',
    appId: '1:26798202385:ios:bae0d1993a104d1e639bb0',
    messagingSenderId: '26798202385',
    projectId: 'myriads-39550',
    storageBucket: 'myriads-39550.appspot.com',
    iosBundleId: 'com.example.myriads.RunnerTests',
  );
}
